FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y curl && \
    apt-get install -y git

# Install Node.js
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs

# Install GitHub CLI (gh)
# RUN apt-get install -y gh

WORKDIR /app

COPY package.json package.json

RUN npm install

COPY . .

RUN chmod +x main.sh 

CMD ["./main.sh"]
